configfile: "config/config.yaml"

import os

# Membaca konfigurasi dari config.yaml
VIRUSES = config["viruses"].keys()
PROTEINS = {}
for v in VIRUSES:
    PROTEINS[v] = config["viruses"][v]["proteins"]

# Define WORKDIR based on config to isolate runs per project name
WORKDIR = f"{config['outdir']}/{config['project_name']}"

# Menyiapkan list target spesifik agar tidak terjadi kombinasi silang (cross-product) antar virus dan protein
TARGETS = []
for v in VIRUSES:
    for p in PROTEINS[v]:
        TARGETS.append(f"{WORKDIR}/04_selection/{v}/{p}_selection_results.txt")
        TARGETS.append(f"{WORKDIR}/05_structure/{v}/{p}_3d_view.html")
        
# Tambahkan target final statistik
TARGETS.append(f"{WORKDIR}/06_statistics/convergent_signature_matrix.csv")
TARGETS.append(f"{WORKDIR}/06_statistics/jaccard_similarity_heatmap.png")
TARGETS.append(f"{WORKDIR}/06_statistics/selection_phenotype_correlation.png")

rule all:
    input:
        TARGETS

# Include rule modules
include: "rules/01_fetch_and_qc.smk"
include: "rules/02_alignment.smk"
include: "rules/03_phylogeny.smk"
include: "rules/04_selection.smk"
include: "rules/05_structural_mapping.smk"
include: "rules/06_statistics_convergence.smk"
